import argparse
from pathlib import Path

from sentiment_analyzer.dashboard import write_dashboard


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a portable self-contained emotion dashboard from "
            "aggregated temporal tables."
        )
    )
    parser.add_argument(
        "temporal_dir",
        help="Directory generated by sentiment-temporal-analysis.",
    )
    parser.add_argument(
        "--statistical-dir",
        help="Optional directory generated by statistical analysis.",
    )
    parser.add_argument(
        "--output",
        default="outputs/emotion_dashboard.html",
        help="Destination HTML file.",
    )
    args = parser.parse_args()

    output = write_dashboard(
        args.temporal_dir,
        args.output,
        statistical_dir=args.statistical_dir,
    )
    print(f"Self-contained dashboard saved to: {Path(output).resolve()}")


if __name__ == "__main__":
    main()
